Repository TMC-Software/TheCodingBot, pull requests merged in 2022-02, with the labels that each got.

#14 Add guildMemberRemove for #13
  src/app/evts/guildMemberRemove.js
Labels: enhancement

#16 Add messageDeleteBulk for #15
  src/app/cfg/app.js
  src/app/evts/messageDelete.js
  src/app/evts/messageDeleteBulk.js
  src/app/evts/messageUpdate.js
Labels: enhancement

#17 v5 Update 7 part 1
  src/app/cmds/Fun/8ball.js
  src/app/cmds/Moderation/purge.js
  src/bot.js
Labels: bug, enhancement, bugfix

#18 v5 Update 8 Part 1
  package-lock.json
  package.json
  src/app/cfg/app.js
  src/app/cmds/General/about.js
  src/app/extras/extras.json.example
Labels: enhancement, bugfix
